[기능구현] firebase 세팅 및 API 추가
FECrash/here-your-duckdam pull request #9
Opened 2022-09-06 16:01 UTC by areumsheep

## 작업 내용
- firebase 환경 세팅
- 덕담 조회 / 추가 API 추가

API 파라미터나 Path 같은 내용은 이슈를 참고해주세요!
`.env` 파일의 경우 팀 노션에 올려놓았습니다.

## 관련 이슈
#8 

## 참고 자료 (option)
조회 API: https://firebase.google.com/docs/firestore/query-data/get-data
추가 API: https://firebase.google.com/docs/firestore/manage-data/add-data

2022-09-06 16:33 UTC, dahye1013 requested changes
수고하셨어요ㅎㅎㅎ 코멘트만 조금 남겨두었어요!
`yarn.lock` conflict가 난 것만 해결해주시면 좋을 것 같아요!

2022-09-06 16:33 UTC, dahye1013 commented on pages/api/duckdam.add.ts
> +    console.log(req.body);
앗 콘솔로그가 남아있어요!

2022-09-06 16:33 UTC, dahye1013 commented on pages/api/duckdam.add.ts
> +  if (req.method === 'POST') {
핸들러는 구현 Post, Get이라는 분기가 필요한가요?? 
만약 분기가 필요하다면 `early return` 을 써볼 수도 있을 것 같아요!

2022-09-06 16:33 UTC, dahye1013 commented on pages/api/duckdam.add.ts
> +    console.log('Document written with ID: ', docRef.id);
요기도 콘솔로그!

2022-09-06 23:52 UTC, jlee0505 commented
수고하셨습니다! 👍👍👍

2022-09-07 01:11 UTC, dahye1013 commented
conflict건만 resolve해서 머지해둘게요 :) 
콘솔로그는 한번에 잡으면 될 것 같아서요. (빌드할때 제거하는 방법도 있구요)

2022-09-07 01:11 UTC, merged

2022-09-07 05:03 UTC, areumsheep commented
> conflict건만 resolve해서 머지해둘게요 :) 콘솔로그는 한번에 잡으면 될 것 같아서요. (빌드할때 제거하는 방법도 있구요)

감사합니다! 위에 말씀해주신 피드백 적용해서 다음 PR에 적용해볼게요!!